### ISSUE TITLE
Pick data set, download

### ISSUE THREAD

**Issue by MattClarkson** [00bryan123/DeepReg#3]
@YipengHu to pick

**Comment by YipengHu** [comment]
http://medicaldecathlon.com/
download the data from the `Pancreas Tumour` task.

**Comment by MattClarkson** [comment]
If you are struggling to scp to CS cluster.

* Log into department using ThinLinc client
* Start browser
* Download same dataset to CS home drive
* scp from CS home drive to CS cluster home drive

Let me know if there is a problem.
