### ISSUE TITLE
Download liver data + organise + load

### ISSUE THREAD

**Issue by MattClarkson** [00bryan123/DeepReg#5]
* From medical decathon (see last week) - download liver 3
* Look at data, check you understand format/images/labels
* Read DeepReg docs and understand data structure
* Write/Configure data loader for
  * Unsupervised
  * Weakly supervised

**Comment by YipengHu** [comment]
the data loader doc: https://deepreg.readthedocs.io/en/latest/docs/dataset_loader.html#unpaired-images

**Comment by MattClarkson** [comment]
Essentially - we can now load medical decathlon dataset.
Resolved .nii.gz issue by uncompressing.
